version: '3'

volumes:
  pg_data:
  static:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: shinket7/taski_backend:latest
    env_file: .env
    volumes:
      - static:/backend_static/
    depends_on:
      - db
  frontend:
    image: shinket7/taski_frontend:latest
    env_file: .env
    volumes:
      - static:/frontend_static
    command: cp -r /app/build/. /frontend_static/
  gateway:
    image: shinket7/taski_gateway:latest
    volumes:
      - static:/staticfiles
    ports:
      - 8000:80
